dist: trusty
sudo: required
osx_image: xcode8
language: java

os:
  - linux
  # - osx DISABLE FOR NOW UNTIL LINUX WORKING

env:
#  - BAZEL=0.24.0 LANG=java RULE=proto_compile PASS
#  - BAZEL=0.24.0 LANG=java RULE=proto_library PASS
#  - BAZEL=0.24.0 LANG=java RULE=grpc_compile PASS
#  - BAZEL=0.24.0 LANG=java RULE=grpc_library PASS
#  - BAZEL=0.24.0 LANG=go RULE=proto_compile PASS
#  - BAZEL=0.24.0 LANG=go RULE=proto_library PASS
#  - BAZEL=0.24.0 LANG=go RULE=grpc_compile PASS
#  - BAZEL=0.24.0 LANG=go RULE=grpc_library PASS
 - BAZEL=0.24.0 LANG=python RULE=proto_compile
 - BAZEL=0.24.0 LANG=python RULE=proto_library
 - BAZEL=0.24.0 LANG=python RULE=grpc_compile
 - BAZEL=0.24.0 LANG=python RULE=grpc_library

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      OS=linux
    fi
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-${OS}-x86_64.sh"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    cd "${LANG}/example/${LANG}_${RULE}" && bazel build //:*

notifications:
  email: false
